# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20170104_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
