image: docker:19.03.0

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.0-dind

before_script:
  - docker info

buildcaddy:
  stage: build
  script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f compose/caddy/Dockerfile -t registry.gitlab.com/maidstone-hackspace/caddy:latest .
    - docker push registry.gitlab.com/maidstone-hackspace/caddy:latest

build:
  stage: build
  script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/maidstone-hackspace/maidstone-hackspace-website:latest .
    - docker push registry.gitlab.com/maidstone-hackspace/maidstone-hackspace-website:latest
