version: '2'

volumes:
  sockets:
    external: true
  postgres_data:
    driver: local
  postgres_backup:
    driver: local

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    command: /live-gunicorn-mhackspace.sh
    env_file: .env
    volumes:
      - .:/app
      - sockets:/data/sockets



  node:
    image: node:7-onbuild
    command: npm install
    volumes:
      - ./:/usr/src/app

  redis:
    image: redis:latest

