version: '2'

volumes:
  sockets:
    external: true
  postgres_data:
    driver: local
  postgres_backup:
    driver: local

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env
    restart: always

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - directory
      - redis
    command: /live-gunicorn-mhackspace.sh
    env_file: .env
    volumes:
      - .:/app
      - sockets:/data/sockets
    restart: always

  redis:
    image: redis:latest
    restart: always


  huey:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - directory
      - redis
    command: python manage.py run_huey
    env_file: .env
    volumes:
      - .:/app
      - sockets:/data/sockets

  directory:
    image: osixia/openldap:1.2.0
    env_file: .env
