version: '2'

volumes:
  sockets:
    external: true
  postgres_data:
    driver: local
  postgres_backup:
    driver: local

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env
    restart: always

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      # - redis
    command: /stage-gunicorn-mhackspace.sh
    env_file: .env
    volumes:
      - .:/app
      - sockets:/data/sockets
    restart: always

  redis:
    image: redis:latest
    restart: always

  celeryworker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    command: celery -A mhackspace.celeryapp worker -l INFO
    restart: always

  celerybeat:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    command: celery -A mhackspace.celeryapp beat -l INFO
    restart: always

  directory:
    image: osixia/openldap:1.2.0
    ports:
      - "0.0.0.0:389:389"
    env_file: .env
