# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequests',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
