# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_userrequests_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequests',
            name='request_type',
            field=models.IntegerField(choices=[(1, 'Equipment request'), (2, 'Educational request'), (3, 'Training request')], default=1),
            preserve_default=False,
        ),
    ]
