# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_userrequests_request_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrequests',
            options={'ordering': ('cost',)},
        ),
        migrations.AddField(
            model_name='userrequests',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
    ]
