# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_auto_20170904_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequests',
            name='title',
            field=models.CharField(default='', help_text='Whats being requested ?', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userrequests',
            name='description',
            field=models.TextField(help_text="detail of what's being requested and where it can be purchased"),
        ),
        migrations.AlterField(
            model_name='userrequests',
            name='request_type',
            field=models.IntegerField(choices=[(0, 'Equipment request'), (1, 'Educational request'), (2, 'Training request')]),
        ),
    ]
