# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_auto_20170906_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequests',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Leave blank, if no associated cost, or add estimated cost if not sure.', max_digits=6),
        ),
    ]
