# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 17:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0007_auto_20170919_2023'),
    ]

    operations = [
        migrations.RenameModel('UserRequests', 'UserRequest'),
    ]
