# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_userrequest_acquired'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Your comments')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userrequest',
            options={'ordering': ('acquired', 'created_date')},
        ),
        migrations.AddField(
            model_name='userrequestcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.UserRequest'),
        ),
    ]
