# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_auto_20180115_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequestcomments',
            name='request',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='requests.UserRequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='acquired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userrequestcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
