# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0011_auto_20180115_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRequestComments',
            new_name='UserRequestsComment',
        ),
    ]
