# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-03 20:19
from __future__ import unicode_literals

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0012_auto_20180115_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='description',
            field=martor.models.MartorField(help_text="detail of what's being requested and where it can be purchased"),
        ),
        migrations.AlterField(
            model_name='userrequestscomment',
            name='comment',
            field=martor.models.MartorField(help_text='Your comments'),
        ),
    ]
