# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 19:11
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.utils
import stdimage.validators
import dynamic_filenames


class Migration(migrations.Migration):

    dependencies = [("base", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="bannerimages",
            name="scaled_image",
            field=stdimage.models.StdImageField(
                blank=True,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="{model_name}/{instance.title:slug}{ext}"
                ),
                validators=[stdimage.validators.MinSizeValidator(800, 600)],
            ),
        )
    ]
