# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 21:46
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.utils
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170214_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimages',
            name='scaled_image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('title'), validators=[stdimage.validators.MinSizeValidator(1200, 300)]),
        ),
    ]
