# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170215_2146'),
        ('base', '0003_auto_20170222_2055'),
    ]

    operations = [
    ]
