# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:10
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.utils
import stdimage.validators
import dynamic_filenames


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_merge_20170226_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimage',
            name='original_image',
        ),
        migrations.RemoveField(
            model_name='bannerimage',
            name='scaled_image',
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='image',
            field=stdimage.models.StdImageField(default='', upload_to=dynamic_filenames.FilePattern(filename_pattern="{model_name}/{instance.title:slug}{ext}"), validators=[stdimage.validators.MinSizeValidator(1200, 300)]),
            preserve_default=False,
        ),
    ]
