# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 18:04
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.utils
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20170228_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('title'), validators=[stdimage.validators.MinSizeValidator(2400, 600)]),
        ),
    ]
