# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('updated_date',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='published_date',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Maidstone Hackspace Blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='members_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='url', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='url', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
