# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170215_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='members_only',
        ),
        migrations.AddField(
            model_name='post',
            name='members_only',
            field=models.BooleanField(default=False),
        ),
    ]
