# Generated by Django 2.1.1 on 2018-09-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_added_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sent_on_social',
            field=models.BooleanField(default=False),
        ),
    ]
