# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 07:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceauth',
            name='device',
        ),
        migrations.RemoveField(
            model_name='deviceauth',
            name='user',
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rfid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DeviceAuth',
        ),
    ]
