# Generated by Django 2.1.1 on 2018-10-17 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rfid_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='deviceauth',
            name='device',
        ),
        migrations.RemoveField(
            model_name='deviceauth',
            name='rfid',
        ),
        migrations.RemoveField(
            model_name='device',
            name='members',
        ),
        migrations.AddField(
            model_name='device',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DeviceAuth',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfid.Device'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='rfid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Rfid'),
        ),
    ]
