# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0002_auto_20170420_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfid.Device')),
                ('rfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfid.Rfid')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='members',
            field=models.ManyToManyField(through='rfid.DeviceAuth', to='rfid.Rfid'),
        ),
    ]
