# Generated by Django 2.2.3 on 2019-09-29 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0002_rfid_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='access_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
