# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170222_2055'),
        ('users', '0002_user_public'),
    ]

    operations = [
    ]
