# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 15:57
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20170226_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='_image',
            field=stdimage.models.StdImageField(blank=True, db_column='image', null=True, upload_to='avatars/'),
        ),
    ]
