# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170813_1557'),
        ('users', '0004_rfid'),
    ]

    operations = [
    ]
