# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20170912_2037'),
        ('users', '0005_merge_20170913_0740'),
    ]

    operations = [
    ]
