# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20170913_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid',
            name='code',
            field=models.CharField(max_length=7),
        ),
    ]
