# Generated by Django 2.1.1 on 2018-10-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180904_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='over_18',
            field=models.BooleanField(default=False, help_text='Please confirm your over 18'),
        ),
    ]
