# Generated by Django 2.1.1 on 2018-10-11 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_membership_over_18'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='membership',
            name='payment_date',
            field=models.DateTimeField(default=None),
        ),
    ]
