# Generated by Django 2.1.1 on 2018-10-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181011_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='payment_date',
            field=models.DateTimeField(default=None),
        ),
    ]
