# Generated by Django 2.1.2 on 2018-10-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rfid_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
